name: Wazuh CI/CD - Deploy Local

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  deploy:
    name: Deploy Local e Reiniciar Wazuh
    runs-on: self-hosted
    steps:
      - name: Fazer checkout do repositório
        uses: actions/checkout@v2

      - name: Copiar Decoders para o Wazuh Manager com sudo
        run: |
          echo "Copiando arquivos de Decoders..."
          sudo cp -v Decoders/*.xml /var/ossec/etc/decoders/
          sudo chown -R wazuh:wazuh /var/ossec/etc/decoders/

      - name: Copiar Regras para o Wazuh Manager com sudo
        run: |
          echo "Copiando arquivos de Regras..."
          sudo cp -v Rules/*.xml /var/ossec/etc/rules/
          sudo chown -R wazuh:wazuh /var/ossec/etc/rules/

      - name: Copiar Arquivos de grupos para o Wazuh Manager com sudo
        run: |
          echo "Copiando arquivos de grupos..."
          sudo cp -v Shared/* /var/ossec/etc/shared/
          sudo chown -R wazuh:wazuh /var/ossec/etc/shared/

      - name: Reiniciar Wazuh Manager
        run: |
          echo "Reiniciando o serviço do Wazuh Manager..."
          sudo systemctl restart wazuh-manager
